import type { NextPage } from "next";
import Head from "next/head";
import { Grid, Paper } from "@mui/material";
import { ListWrapper } from "../src/components/ui/ListWrapper/list";
import MapBox from "../src/components/ui/Map/MapBox";
import { getAuth, signOut } from "firebase/auth";
import Wrapper from "../src/components/ui/Wrapper/wrapper";
import { useRouter } from "next/router";

// const auth = getAuth();

const Home: NextPage = () => {
  const router = useRouter();

  const handleSignOut = () => {
    // signOut(auth)
    //   .then(() => {
    //     router.push("/");
    //     // Sign-out successful.
    //   })
    //   .catch((error) => {
    //     // An error happened.
    //   });
  };

  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container spacing={2}>
          <Grid item>
            <ListWrapper />
          </Grid>

          <Grid item xs={12} sm={6} lg={9}>
            <Paper sx={{ height: 600 }}>
              <MapBox />
            </Paper>
          </Grid>
        </Grid>
      </main>

      <button onClick={handleSignOut}>Sign Out</button>
    </Wrapper>
  );
};

export default Home;
